### ISSUE TITLE
svgWrap: false does not work

### ISSUE THREAD

**Issue by brokolja** [mastersign/htinliner#1]
Hi,

thx for the nice work. But the option function evaluates: false options to defaultOptions...

Greets,
K

**Comment by koljakutschera** [comment]
Untestet fix: 
```js
var option = function (name, opt) {
	var opt = opt || {};
	return opt[name] === false ? false : opt[name];
};
```
...

Would be nice to see a new version on npm :)

**Comment by koljakutschera** [comment]
Fix does not include defOpt ...

**Comment by mastersign** [comment]
Thanks for the heads up. I am extending the tests.
